title: Giuseppe Palestra
description: Giuseppe Palestra's Personal Page
url: "http://www.giuseppepalestra.it"
author: Giuseppe Palestra

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-toc
  - jekyll-last-modified-at

twitter:
  username: giupalestra
social:
  name: Giuseppe Palestra
  links: 
    - https://twitter.com/giupalestra
    - https://www.facebook.com/giuseppe.palestra
    - https://www.instagram.com/giuseppe_palestra/
    - https://it.linkedin.com/in/giuseppepalestra
    - https://www.researchgate.net/profile/Giuseppe_Palestra
    - https://github.com/giuseppepalestra
google_site_verification: googlee691e96cc4bf3ed8.html
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
email: info AT giuseppepalestra.it

dateModified: 2018-02-18 15:23:29
